### ISSUE TITLE
Add Extension icon

### ISSUE THREAD

**Issue by coliff** [ruiquelhas/vscode-lowercase#2]
An icon for each extension shows in list of installed extensions and on the VS Code Extension Marketplace. It'd be nice to add one for vscode-lowercase.

If you'd like me to create a quick one and open a PR with it - let me know. :-)

**Comment by ruiquelhas** [comment]
I don't feel particularly creative at the moment :stuck_out_tongue: but I guess that might be an interesting idea. Yes, feel free to open the PR!
